jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Patlenain\GasBundle\Entity\Utilisateur:
            algorithm:          sha512
            encode_as_base64:   false
            iterations:         1

    providers:
        gas_db:
            entity:     { class: PatlenainGasBundle:Utilisateur, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/(login|logout)$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: patlenain_gas_login_check
                login_path: patlenain_gas_login
                post_only:  true
#                crsf_provider:  form.crsf_provider
            logout:
                path:   patlenain_gas_logout
                target: patlenain_gas_index
