<?php

namespace Patlenain\GasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnneeRepository extends EntityRepository
{
	/**
	 * @return QueryBuilder
	 */
	function listAll()
	{
		return $this->createQueryBuilder('annee')
			->addOrderBy('annee.libelle', 'DESC');
	}
	/**
	 * @return QueryBuilder
	 */
	function getDerniereAnnee()
	{
		return $this->createQueryBuilder('annee')
			->addOrderBy('annee.libelle', 'DESC')
			->setMaxResults(1);
	}
}
