<?php

namespace Patlenain\GasBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
	/**
	 * @return QueryBuilder
	 */
	public function listAll()
	{
		return $this->createQueryBuilder('utilisateur')
			->addOrderBy("utilisateur.username");
	}
}
